# Generated by Django 5.2 on 2025-04-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_atividade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
