# Generated by Django 5.2 on 2025-04-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nmusuario', models.CharField(max_length=50)),
                ('emailusuario', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('dtnascimento', models.DateField()),
                ('flsituacao', models.BooleanField(default=True)),
                ('nivelusuario', models.IntegerField(default=1)),
                ('expusuario', models.SmallIntegerField(default=0)),
                ('tipousuario', models.CharField(choices=[('admin', 'Administrador'), ('comum', 'Comum')], default='comum', max_length=10)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
