# Generated by Django 5.2 on 2025-04-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_ultima_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='streak_semanal',
            field=models.IntegerField(default=0),
        ),
    ]
