# Generated by Django 5.2 on 2025-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_senha_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='streak_semanal',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.CharField(choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3')], default='avatar1.png', max_length=100),
        ),
    ]
