# Generated by Django 5.1.7 on 2025-04-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idatividade', models.AutoField(primary_key=True, serialize=False)),
                ('nmatividade', models.CharField(max_length=100)),
                ('peso', models.CharField(choices=[('muito_facil', 'Muito fácil'), ('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito difícil')], max_length=20)),
                ('situacao', models.CharField(choices=[('iniciada', 'Iniciada'), ('pausada', 'Pausada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20)),
                ('recorrencia', models.CharField(choices=[('unica', 'Única'), ('habitual', 'Habitual')], max_length=20)),
                ('dtatividade', models.DateField()),
                ('dtatividaderealizada', models.DateField(blank=True, null=True)),
                ('tpestimado', models.IntegerField()),
                ('dsatividade', models.TextField(blank=True)),
                ('expatividade', models.SmallIntegerField(default=0)),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
    ]
