# Generated by Django 5.2 on 2025-06-05 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividadeconcluidas',
            name='idatividade',
            field=models.ForeignKey(db_column='idatividade', on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade'),
        ),
        migrations.AddField(
            model_name='atividadeconcluidas',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaopomodoro',
            name='idatividade',
            field=models.ForeignKey(db_column='idatividade', on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade'),
        ),
        migrations.AddField(
            model_name='sessaopomodoro',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
