# Generated by Django 5.2 on 2025-04-28 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividade_streak_semanal_atividade_ultima_atividade'),
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoPomodoro',
            fields=[
                ('idsessao', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('nrciclo', models.IntegerField(default=1)),
                ('idatividade', models.ForeignKey(db_column='idatividade', on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'sessoes_pomodoro',
            },
        ),
    ]
