# Generated by Django 5.2 on 2025-04-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0006_alter_atividade_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
    ]
