# Generated by Django 5.2 on 2025-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_atividadeconcluidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dtatividade',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='dtatividaderealizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
