# Generated by Django 5.2 on 2025-05-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('iddesafio', models.AutoField(primary_key=True, serialize=False)),
                ('nmdesafio', models.CharField(max_length=100)),
                ('dsdesafio', models.TextField()),
                ('tipo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('unico', 'Único')], max_length=10)),
                ('dtinicio', models.DateTimeField(blank=True, null=True)),
                ('dtfim', models.DateTimeField(blank=True, null=True)),
                ('expdesafio', models.SmallIntegerField(default=0)),
                ('tipo_logica', models.CharField(max_length=50)),
                ('parametro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'desafios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDesafio',
            fields=[
                ('idusuariodesafio', models.AutoField(primary_key=True, serialize=False)),
                ('flsituacao', models.BooleanField(default=True)),
                ('dtpremiacao', models.DateTimeField(blank=True, null=True)),
                ('iddesafio', models.ForeignKey(db_column='iddesafio', on_delete=django.db.models.deletion.CASCADE, to='desafios.desafio')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_desafios',
                'unique_together': {('idusuario', 'iddesafio')},
            },
        ),
    ]
