# Generated by Django 5.2 on 2025-06-05 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desafios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodesafio',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usuariodesafio',
            unique_together={('idusuario', 'iddesafio')},
        ),
    ]
