# Generated by Django 5.2 on 2025-06-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('idconquista', models.AutoField(primary_key=True, serialize=False)),
                ('nmconquista', models.CharField(max_length=100)),
                ('dsconquista', models.TextField()),
                ('nmimagem', models.TextField(blank=True)),
                ('expconquista', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'conquistas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioConquista',
            fields=[
                ('idusuarioconquista', models.AutoField(primary_key=True, serialize=False)),
                ('dtconcessao', models.DateTimeField(auto_now_add=True)),
                ('idconquista', models.ForeignKey(db_column='idconquista', on_delete=django.db.models.deletion.CASCADE, to='conquistas.conquista')),
            ],
            options={
                'db_table': 'usuario_conquistas',
            },
        ),
    ]
