# Generated by Django 5.2 on 2025-04-24 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idatividade', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmatividade', models.CharField(max_length=100)),
                ('peso', models.CharField(choices=[('muito_facil', 'Muito fácil'), ('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito difícil')], max_length=20)),
                ('situacao', models.CharField(choices=[('iniciada', 'Iniciada'), ('pausada', 'Pausada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20)),
                ('recorrencia', models.CharField(choices=[('unica', 'Única'), ('habitual', 'Habitual')], max_length=20)),
                ('dtatividade', models.DateField()),
                ('dtatividaderealizada', models.DateField(blank=True, null=True)),
                ('tpestimado', models.IntegerField()),
                ('dsatividade', models.TextField(blank=True)),
                ('expatividade', models.SmallIntegerField(default=0)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
    ]
