# Generated by Django 5.2 on 2025-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='recorrencia',
            field=models.CharField(choices=[('unica', 'Única'), ('recorrente', 'Recorrente')], max_length=20),
        ),
    ]
