# Generated by Django 5.2 on 2025-04-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_remove_atividade_idatividade_atividade_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='id',
        ),
        migrations.AddField(
            model_name='atividade',
            name='idatividade',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
