# Generated by Django 5.2 on 2025-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_atividade_recorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='streak_semanal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atividade',
            name='ultima_atividade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
