# Generated by Django 5.2 on 2025-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_sessaopomodoro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='streak_semanal',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='ultima_atividade',
        ),
    ]
