# Generated by Django 5.2 on 2025-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_remove_atividade_streak_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
    ]
