# Generated by Django 5.2 on 2025-05-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0007_alter_atividade_situacao'),
        ('usuarios', '0004_usuario_streak_semanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeConcluidas',
            fields=[
                ('idatividade_concluida', models.AutoField(primary_key=True, serialize=False)),
                ('dtconclusao', models.DateTimeField()),
                ('idatividade', models.ForeignKey(db_column='idatividade', on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'atividades_concluidas',
            },
        ),
    ]
